---
abstract: "[One line description of module's purpose here]"
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: cPanel-RESTivus
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
version: '0.01'
